version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt-get -qq update
      - run: apt-get -qq -y install git curl software-properties-common > /dev/null
      - checkout
      - setup_remote_docker
      - run: curl -fsSL https://get.docker.com -o get-docker.sh
      - run: /bin/sh get-docker.sh > /dev/null
      - run: docker version
      - run: install-docker-compose.sh
      - run: docker-compose version
